######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 23 21:39:51 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../model/clist.h tst_clisttest.moc
SOURCES += tst_clisttest.cpp
