######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 23 23:53:35 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../model/base.h ../../model/ingridiente.h tst_baseingrtest.moc
SOURCES += tst_baseingrtest.cpp ../../model/base.cpp ../../model/ingridiente.cpp
