######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 24 01:31:06 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../model/drink.h \
           ../../model/ingridiente.h \
           ../../model/base.h \
           ../../model/aromatizzante.h \
           ../../model/colorante.h \
           tst_drinktest.moc
SOURCES += tst_drinktest.cpp \
           ../../model/drink.cpp \
           ../../model/ingridiente.cpp \
           ../../model/base.cpp \
           ../../model/aromatizzante.cpp \
           ../../model/colorante.cpp
