######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 24 20:13:00 2016
######################################################################

QT += testlib xml
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../model/ricettario.h \
           ../../model/clist.h \
           ../../model/cocktail.h \
           ../../model/drink.h \
           ../../model/ingridiente.h \
           ../../model/base.h \
           ../../model/aromatizzante.h \
           ../../model/colorante.h \
           tst_ricettariotest.moc
SOURCES += tst_ricettariotest.cpp \
           ../../model/ricettario.cpp \
           ../../model/cocktail.cpp \
           ../../model/drink.cpp \
           ../../model/ingridiente.cpp \
           ../../model/base.cpp \
           ../../model/aromatizzante.cpp \
           ../../model/colorante.cpp
