######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 24 13:24:56 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../model/cocktail.h \
           ../../model/drink.h \
           ../../model/ingridiente.h \
           ../../model/base.h \
           ../../model/aromatizzante.h \
           ../../model/colorante.h \
           tst_cocktailtest.moc
SOURCES += tst_cocktailtest.cpp \
           ../../model/cocktail.cpp \
           ../../model/drink.cpp \
           ../../model/ingridiente.cpp \
           ../../model/base.cpp \
           ../../model/aromatizzante.cpp \
           ../../model/colorante.cpp
